plugins {
    id 'java'
    id 'application'
}

group = 'app.belgarion.java.db_files'
version = '1.0'

repositories {
    mavenCentral()
}
run {
    standardInput = System.in
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'org.jetbrains:annotations:24.0.1'
}


test {
    useJUnitPlatform()
}
application {
    mainClass.set("app.belgarion.java.db_files.Main")
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
